INSERT INTO Usuarios(Nombre, Edad, Activo, FecCreacion, FecActualizacion) VALUES('Max Castro Vidal', 48, 1, GETDATE(), GETDATE())
INSERT INTO Usuarios(Nombre, Edad, Activo, FecCreacion, FecActualizacion) VALUES('Pedro Vargas Rojas', 20, 1, GETDATE(), GETDATE())
INSERT INTO Usuarios(Nombre, Edad, Activo, FecCreacion, FecActualizacion) VALUES('Juan Pablo Segovia', 24, 1, GETDATE()-5, GETDATE()-5)
INSERT INTO Usuarios(Nombre, Edad, Activo, FecCreacion, FecActualizacion) VALUES('Claudia Martinez Gajardo', 28, 1, GETDATE()-10, GETDATE()-10)
INSERT INTO Usuarios(Nombre, Edad, Activo, FecCreacion, FecActualizacion) VALUES('Hernán Cubillos Vásquez', 32, 1, GETDATE()-20, GETDATE()-20)
INSERT INTO Usuarios(Nombre, Edad, Activo, FecCreacion, FecActualizacion) VALUES('Patricia Gamero Fuentes', 36, 0, GETDATE(), GETDATE())
INSERT INTO Usuarios(Nombre, Edad, Activo, FecCreacion, FecActualizacion) VALUES('Isabel Sepúlveda Blanco', 40, 0, GETDATE()-5, GETDATE()-5)
INSERT INTO Usuarios(Nombre, Edad, Activo, FecCreacion, FecActualizacion) VALUES('Juan Carlos Gómez Vega', 44, 0, GETDATE()-10, GETDATE()-10)
INSERT INTO Usuarios(Nombre, Edad, Activo, FecCreacion, FecActualizacion) VALUES('Luis Sánchez Valenzuela', 25, 1, GETDATE()-20, GETDATE()-20)
INSERT INTO Usuarios(Nombre, Edad, Activo, FecCreacion, FecActualizacion) VALUES('Héctor Guerrero Lobos', 33, 1, GETDATE(), GETDATE())
INSERT INTO Usuarios(Nombre, Edad, Activo, FecCreacion, FecActualizacion) VALUES('Gustavo Garagena Tobar', 21, 1, GETDATE()-5, GETDATE()-5)
INSERT INTO Usuarios(Nombre, Edad, Activo, FecCreacion, FecActualizacion) VALUES('Pedro Reyes Fuentealva', 48, 0, GETDATE()-10, GETDATE()-10)
INSERT INTO Usuarios(Nombre, Edad, Activo, FecCreacion, FecActualizacion) VALUES('Felipe Massú Contreras', 60, 1, GETDATE()-20, GETDATE()-20)
INSERT INTO Usuarios(Nombre, Edad, Activo, FecCreacion, FecActualizacion) VALUES('Jeanette Fernandes Casas', 55, 1, GETDATE(), GETDATE())
INSERT INTO Usuarios(Nombre, Edad, Activo, FecCreacion, FecActualizacion) VALUES('Ernesto Aguilera Canales', 30, 0, GETDATE()-1, GETDATE()-1)